# Generated by Django 4.0.2 on 2022-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offres_emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('lien', models.CharField(max_length=100)),
                ('mots_clefs', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offres_emploi_brut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_offre', models.CharField(max_length=100)),
                ('intitule', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dateCreation', models.CharField(max_length=100)),
                ('dateActualisation', models.CharField(max_length=100)),
                ('lieuTravail', models.CharField(max_length=100)),
                ('romeCode', models.CharField(max_length=100)),
                ('romeLibelle', models.CharField(max_length=100)),
                ('appellationlibelle', models.CharField(max_length=100)),
                ('entreprise', models.CharField(max_length=100)),
                ('typeContrat', models.CharField(max_length=100)),
                ('typeContratLibelle', models.CharField(max_length=100)),
                ('natureContrat', models.CharField(max_length=100)),
                ('experienceExige', models.CharField(max_length=100)),
                ('experienceLibelle', models.CharField(max_length=100)),
                ('salaire', models.CharField(max_length=100)),
                ('alternance', models.CharField(max_length=100)),
                ('nombrePostes', models.CharField(max_length=100)),
                ('accessibleTH', models.CharField(max_length=100)),
                ('qualificationCode', models.CharField(max_length=100)),
                ('qualificationLibelle', models.CharField(max_length=100)),
                ('secteurActivit', models.CharField(max_length=100)),
                ('secteurActiviteLibelle', models.CharField(max_length=100)),
                ('origineOffre', models.CharField(max_length=100)),
                ('dureeTravailLibelleConverti', models.CharField(max_length=100)),
                ('deplacementLibelle', models.CharField(max_length=100)),
                ('offresManqueCandidats', models.CharField(max_length=100)),
                ('dureeTravailLibelle', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('qualitesProfessionnelles', models.CharField(max_length=100)),
                ('competences', models.CharField(max_length=100)),
                ('deplacementCode', models.CharField(max_length=100)),
                ('permis', models.CharField(max_length=100)),
                ('langues', models.CharField(max_length=100)),
                ('formations', models.CharField(max_length=100)),
                ('experienceCommentaire', models.CharField(max_length=100)),
                ('agence', models.CharField(max_length=100)),
                ('complementExercice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_clef', models.CharField(max_length=100)),
            ],
        ),
    ]
