# Generated by Django 4.0.2 on 2022-02-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_asso_user_skills_asso_offres_emploi_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asso_offres_emploi_skills',
            name='offres_emploi',
        ),
        migrations.RemoveField(
            model_name='asso_offres_emploi_skills',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Asso_offres_emploi_metiers',
        ),
        migrations.DeleteModel(
            name='Asso_offres_emploi_skills',
        ),
    ]
