# Generated by Django 4.0.2 on 2022-02-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_offres_emploi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asso_offres_emploi_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.CharField(max_length=100)),
                ('offres_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.offres_emploi')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Asso_offres_emploi_metiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.CharField(max_length=100)),
                ('metiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.metiers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.offres_emploi')),
            ],
        ),
    ]
