# Generated by Django 4.0.2 on 2022-02-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_asso_offres_emploi_skills_asso_offres_emploi_metiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offres_emploi',
            name='id_offre',
        ),
    ]
