# Generated by Django 4.0.2 on 2022-02-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_offres_emploi_brut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asso_offres_emploi_skills',
            name='offres_emploi',
        ),
        migrations.RemoveField(
            model_name='asso_offres_emploi_skills',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='asso_user_skills',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='asso_user_skills',
            name='user',
        ),
        migrations.DeleteModel(
            name='Asso_offres_emploi_metiers',
        ),
        migrations.DeleteModel(
            name='Asso_offres_emploi_skills',
        ),
        migrations.DeleteModel(
            name='Asso_user_skills',
        ),
    ]
