# Generated by Django 4.0.2 on 2022-02-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_remove_asso_offres_emploi_skills_offres_emploi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offres_emploi',
        ),
    ]
