# Generated by Django 4.0.3 on 2022-03-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0013_asso_user_skills_asso_offres_emploi_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asso_user_skills',
            name='precision',
        ),
    ]
